name: Cloud189Checkin
2
​
3
on:
4
  push:
5
    branches: [ master ]
6
  pull_request:
7
    branches: [ master ]
8
  schedule:
9
    - cron: 0 2,14 * * *
10
​
11
jobs:
12
  check-in:
13
    runs-on: ubuntu-latest
14
​
15
    steps:
16
    - uses: actions/checkout@v2
17
​
18
    - name: Install Python
19
      run: |
20
        sudo apt update && \
21
        sudo apt install python3
22
      
23
    - name: requirements
24
      run: |
25
        pip3 install -r requirements.txt
26
        
27
    - name: Checkin
28
      run: |
29
        user='${{ secrets.USER }}'
30
        pwd='${{ secrets.PWD }}'
31
        
32
        user_list=()
33
        pwd_list=()
34
​
35
        IFS=","
36
​
37
        for u in ${user[*]}
38
        do
39
        user_list[${#user_list[*]}]=${u}
40
        done
41
​
42
        for p in ${pwd[*]}
43
        do
44
        pwd_list[${#pwd_list[*]}]=${p}
45
        done
46
​
47
        user_num=${#user_list[*]}
48
        pwd_num=${#pwd_list[*]}
49
​
50
        if [ $user_num != $pwd_num ];then
51
        echo "账号和密码个数不对应"
52
        exit 1
53
        else
54
        echo "共有 $user_num 个账号，即将开始签到"
55
        fi
56
​
57
        for ((i=0;i<$user_num;i++))
58
        do
59
        python3 checkin.py --username ${user_list[$i]} --password ${pwd_list[$i]}
60
        done
